esphome:
  name: halo-v1
  friendly_name: Halo Air Quality Sensor
  name_add_mac_suffix: true
  platformio_options:
    upload_speed: 921600
    build_unflags: -Werror=all
    board_build.flash_mode: qio
    board_build.prsam_type: opi
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L

  min_version: 2025.2.0

  project:
    name: "yashmulgaonkar.Halo-v1"
    version: "${version}"

dashboard_import:
  package_import_url: github://splattner/halo/TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1.yaml@main
  import_full_config: true

ota:
  - platform: esphome
    id: ota_default

wifi:
  on_connect:
    - delay: 5s # Gives time for improv results to be transmitted

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Halo Hotspot"

packages:
  remote_package:
    url: https://github.com/splattner/halo/
    ref: main
    files:
      - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1-Core.yaml
    refresh: 0d
